// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://goswhjtnfzbrveojvoij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdvc3doanRuZnpicnZlb2p2b2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjk4MjgsImV4cCI6MjA2OTY0NTgyOH0.agbSUzbbgEJroVajJFl4bEWtx73kg6ZEeRHdYgG9Urs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});